//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hirameku.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hirameku.Data.Properties.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address does not match the expected regex pattern..
        /// </summary>
        internal static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified hash algorithm &apos;{0}&apos; is not available on the host platform..
        /// </summary>
        internal static string InvalidHashAlgorithm {
            get {
                return ResourceManager.GetString("InvalidHashAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified PasswordHashVersion &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidPasswordHashVersion {
            get {
                return ResourceManager.GetString("InvalidPasswordHashVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value encountered is not a valid PasswordHashVersion representation: {0}.
        /// </summary>
        internal static string InvalidPasswordHashVersionRepresentation {
            get {
                return ResourceManager.GetString("InvalidPasswordHashVersionRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified host &apos;{0}&apos; does not match the domain validation pattern &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidVerifyEmailHost {
            get {
                return ResourceManager.GetString("InvalidVerifyEmailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &apos;{0}&apos; has no stored password hash..
        /// </summary>
        internal static string NoStoredPasswordHash {
            get {
                return ResourceManager.GetString("NoStoredPasswordHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s password cannot be saved because it was changed too recently..
        /// </summary>
        internal static string PasswordChangeTooRecent {
            get {
                return ResourceManager.GetString("PasswordChangeTooRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s password cannot be saved because it is identical to the existing one..
        /// </summary>
        internal static string PasswordIsIdentical {
            get {
                return ResourceManager.GetString("PasswordIsIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification cannot be expired because it was created too recently..
        /// </summary>
        internal static string VerificationTooRecent {
            get {
                return ResourceManager.GetString("VerificationTooRecent", resourceCulture);
            }
        }
    }
}
