//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hirameku.Email.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hirameku.Email.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Strict//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;{0}&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;p&gt;A password reset was recently requested for the Hirameku account associated with this email address. If this was you, please use &lt;a href=&quot;{1}&quot;&gt;this link&lt;/a&gt; to reset your password.{2}&lt;/p&gt;
        ///    &lt;p&gt;If this was not you, consider using the link to change your password anyway. This will prevent anyone else from using the link. Additionally, you might w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForgotPasswordHtml {
            get {
                return ResourceManager.GetString("ForgotPasswordHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset requested.
        /// </summary>
        internal static string ForgotPasswordSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password reset was recently requested for the Hirameku account associated with this email address. If this was you, please use this link to reset your password: {0}.{1}
        ///
        ///If this was not you, consider using the link to change your password anyway. This will prevent anyone else from using the link. Additionally, you might want to change your username, as another party either knows it or was able to guess it. We are unable to prevent unauthorized individuals from using the Forgot Password function, so havi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Strict//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;{0}&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;p&gt;The following feedback submission was received from &lt;a href=&quot;mailto:{1}&quot;&gt;{2}&lt;/a&gt;:&lt;/p&gt;
        ///    &lt;p&gt;{3}&lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string SendFeedbackHtml {
            get {
                return ResourceManager.GetString("SendFeedbackHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback received.
        /// </summary>
        internal static string SendFeedbackSubject {
            get {
                return ResourceManager.GetString("SendFeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following feedback submission was received from {0} ({1}):
        ///
        ///{2}.
        /// </summary>
        internal static string SendFeedbackText {
            get {
                return ResourceManager.GetString("SendFeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  This link is valid for {0}..
        /// </summary>
        internal static string ValidityPeriodText {
            get {
                return ResourceManager.GetString("ValidityPeriodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Strict//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;{0}&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;p&gt;A Hirameku account was recently created for your email address. If this was you, please use &lt;a href=&quot;{1}&quot;&gt;this link&lt;/a&gt; to verify your account.{2}&lt;/p&gt;
        ///    &lt;p&gt;If it was not you, please use &lt;a href=&quot;{3}&quot;&gt;this link&lt;/a&gt; to report the misuse of your email. The corresponding Hirameku account will be suspended, and your email address will be barred from [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VerifyEmailHtml {
            get {
                return ResourceManager.GetString("VerifyEmailHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address verification required.
        /// </summary>
        internal static string VerifyEmailSubject {
            get {
                return ResourceManager.GetString("VerifyEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Hirameku account was recently created for your email address. If this was you, please use this link to verify your account: {0}.{1}
        ///
        ///If it was not you, please use this link to report the misuse of your email: {2}. The corresponding Hirameku account will be suspended, and your email address will be barred from further use on the site..
        /// </summary>
        internal static string VerifyEmailText {
            get {
                return ResourceManager.GetString("VerifyEmailText", resourceCulture);
            }
        }
    }
}
